export enum Role {

 ADMIN = 'ADMIN',

MERCHANDISER = 'MERCHANDISER',

STORE_MANAGER = 'STORE_MANAGER',

PURCHASE_MANAGER = 'PURCHASE_MANAGER',

CUTTING_MANAGER = 'CUTTING_MANAGER',

SEWING_MANAGER = 'SEWING_MANAGER',

FINISHING_MANAGER = 'FINISHING_MANAGER',

PACKING_MANAGER = 'PACKING_MANAGER',

PRODUCTION_MANAGER = 'PRODUCTION_MANAGER'


}